df = read.csv("L:/BUT/SD/Promo 2023/cseu/programm r/tp2/fao.csv", header = TRUE, sep = ";", dec = "," )
dim (df)
View (df)
length (df)
class(df)
nrow(df)
summary(df)
qual_alim_moy = sum(df$Dispo_alim / nrow(df))
nb_hab = sum(df$Population, na.rm = TRUE)
et_exp = sd(df$Export_viande, na.rm = TRUE)
et_imp = sd(df$Import_viande, na.rm = TRUE)
median_vol = median(df$Prod_viande, na.rm = TRUE)
quant_dispo = quantile(df$Dispo_alim, probs = c(0,0.25, 0.5, 0.75))
centile = quantile(df$Import_viande, probs = seq(0,1,0.01))
View(df)
rang = order(df$Population, decreasing = FALSE)
View(df)
df = read.csv("L:/BUT/SD/Promo 2023/cseu/programm r/tp2/fao.csv", header = TRUE, sep = ";", dec = "," )
rang = order(df$Population, decreasing = FALSE)
View(df)
kk = head(rang, n = 5)
pays = c(112)
head(df$Population)
resultat = df[ rang , c("Nom" , "Population")]
kkk = head(resultat, n = 5)
View(kkk)
rang = order(df$Population, decreasing = TRUE)
resultat = df[rang, c("Nom", "Population")]
k = head(resultat, n = 5)
View(k)
View(df)
rang = order(df$Prod_viande, decreasing = TRUE)
resultat = df[rang, c("Nom", "Prod_viande")]
k = head(resultat, n = 5)
View(k)
resultat = df[ , c("Nom", "Dispo_alim" > 2300)]
pays = subset(df, df$Dispo_alim > 2300)
View(pays)
nrow(pays)
